"""initial relational schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-06

Creates the core relational tables from the SQLAlchemy metadata (theses,
thesis_assets, evidence, signals, calibration). Kept in sync with the models
for the MVP; finer-grained autogenerated migrations follow as the schema
evolves. The pgvector ``embeddings`` table is created by VectorStore.
"""

from __future__ import annotations

from alembic import op

from turtle_insight.storage.sql_models import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(op.get_bind())
